/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Campaigns: typeof import('./src/components/CampaignsView.vue')['default']
    CampaignsView: typeof import('./src/components/CampaignsView.vue')['default']
    CreateModalCampaigns: typeof import('./src/components/Modals/Create/CreateModalCampaigns.vue')['default']
    CreateModalCampaignsDetail: typeof import('./src/components/Modals/Create/CreateModalCampaignsDetail.vue')['default']
    CreateModalNews: typeof import('./src/components/Modals/Create/CreateModalNews.vue')['default']
    DeleteModal: typeof import('./src/components/Modals/Delete/DeleteModal.vue')['default']
    DetailsView: typeof import('./src/components/DetailsView.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NewsView: typeof import('./src/components/NewsView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateModalCampaigns: typeof import('./src/components/Modals/Update/UpdateModalCampaigns.vue')['default']
    UpdateModalCampaignsDetail: typeof import('./src/components/Modals/Update/UpdateModalCampaignsDetail.vue')['default']
    UpdateModalNews: typeof import('./src/components/Modals/Update/UpdateModalNews.vue')['default']
  }
}
